sudo: false
language: perl
perl:
  - "5.20"
  - "5.16"
  - "5.10"
env:
  - "HARNESS_OPTIONS=j4 TEST_POD=1"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage EV"
  - "cpanm -n --installdeps ."
notifications:
  irc:
    channels: "chat.freenode.net#batcode"
    on_failure: always
    on_success: change
